### ISSUE TITLE
Apply Lip Sync Data

### ISSUE THREAD

**Issue by Mainman002** [turtletooth/tahoma#127]
Trying to import / use animation data to control character portrait lip sync. Doesn't seem to let me change the images with the arrow ui buttons, when loading animation data exported from Papagayo it just shows a single image stretched out on the timeline (no keyframes or animation changes noticeable)

1. select image column
2. right click
3. select "Apply Lip sync data to column"

should be able to change the character face portraits for each syllable so that the image sequence added to the timeline matches an audio file. (speeds up workflow when creating dialogues for games / cutscenes) 

![image](https://user-images.githubusercontent.com/11281480/91627947-ed078480-e980-11ea-817a-25c31cea04ad.png)

 - OS: Windows 10 home premium
 - Tahoma Version: 1.0. Jul 19, 2020 21:30:07
 - GPU: [e.g. NVIDIA GTX 960
 - GPU Driver Version: 451.48

**Comment by artisteacher** [comment]
I can change the drawings using the arrows on macOS but I'm seeing a glitch where vector drawings are duplicated, partially cut off, with artifacts in the lip sync window. This also happens in OT. Definitely makes lining up the drawings difficult if they are not already in the correct order.
<img width="351" alt="Screen Shot 2020-08-29 at 1 37 54 AM" src="https://user-images.githubusercontent.com/21159116/91629610-72e2fa00-e998-11ea-81eb-b1c96cbfe10e.png">
Smart raster levels look a little pixely. Raster lines are broken:
<img width="176" alt="Screen Shot 2020-08-29 at 1 48 55 AM" src="https://user-images.githubusercontent.com/21159116/91629804-12ed5300-e99a-11ea-9242-b9cd85fe2bb3.png">


The lip sync data is applying without issue on my end, though I'm using a .dat file from Rhubarb Lip-Sync, not Papagayo since Papagayo is no longer being maintained for macOS.

**Comment by Mainman002** [comment]
hmm. . . actually as a beginner user of Tahoma, I think the way I was storing asset files was completely wrong xD so I have my assets imported into Tahoma's file browser Cast / Audio. I dragged my different asset folders containing my images and audio into the proper folders, imported, and now I can change the images in the Lip Sync Window

(Sorry about that, I should have known better) Really enjoying this video editor, the performance is soo much better then kdenlive for this type of video editing
