### ISSUE TITLE
can not open the Tahoma.app on mac OSX

### ISSUE THREAD

**Issue by zoth** [turtletooth/tahoma#136]
Downloaded the Tahoma-osx.dmg from https://tahoma2d.org/download/
Expanded the disk image.
Double clicked on Tahoma.app file.
Got this message:
“Tahoma.app” is damaged and can’t be opened.

**Device Information:**
 - OS: macOS 10.15.6

**Comment by manongjohn** [comment]
I also have this issue with openning it in a macOS 10.15 Virtual environment.

I found a temp workaround for now:

1. Make sure you draw the Tahoma.app out of the .dmg file and someplace on your computer.  I will use Desktop for these instructions.
2. Open Terminal.   This should put you in /Users/yourusername
3. cd Desktop
4. Type:   xattr -cr Tahoma.app

Try opening after that.

**Comment by artisteacher** [comment]
Weird. It works fine on 10.14.6. I'll see if I can figure out what's going on in Catalina. Any ideas @manongjohn?

**Comment by manongjohn** [comment]
@artisteacher I think it might be somehow considered a signed app and somehow its not liking it? 

Removing some hidden attribute with `xattr -cr` seems to fix it and also causes it to not be checked by security so it loads successfully.

I tried running in 10.13, but it doesn't like it because it was created with some libs meant for 10.15. I'm a little surprised it works on 10.14 for you.

**Comment by artisteacher** [comment]
Opening unsigned apps on macOS keeps getting more difficult. 

On 10.14, you need to drag the app from the .dmg into a directory - ie. Applications or Desktop or etc. To open, right-click in Finder & choose open. Select open anyways - but the app doesn't open. Try to open again normally, and it opens.

When everything is working on 10.15, after placing Tahoma in a directory & trying to open, in System Preferences -> Security & Privacy -> General, Tahoma needs to be granted permission to open. Afterwards opening normally works.

I'm building in Xcode with 10.9 as the deployment target, so it's interesting that it won't open in 10.13. I have updated to 10.15.6 & the latest version of Xcode since making the beta release. I wonder if that made a difference?

**Comment by manongjohn** [comment]
I don't have this problem with OTX, which I know is unsigned.

Since both apps are downloaded off the net, it is automatically flagged with com.apple.quarantine as soon as you pull it put of .dmg.

When I try OTX, it throws error that it cannot validate developer sinces it's unsigned but allows me to release it in Security settings. 

Tahoma appears to be signed? Instead of giving me developer validation error it just thinks its damaged and won't open or even give option in Security.

**Comment by artisteacher** [comment]
It should be unsigned. Does anything look wrong in BundleInfo.plist.in?

**Comment by zoth** [comment]
thanks
that worked for me

**Comment by manongjohn** [comment]
Something is signed? Here is a comparison of Tahoma and OTX when I check it:

![image](https://user-images.githubusercontent.com/19245851/92289667-3b67d680-eedf-11ea-87c6-a11ab59dbc44.png)

I also notice Tahoma has additional files/folders that OTX doesn't have
   Tahoma.app/Content/PkgInfo
   Tahoma.app/Content/_CodeSignature/CodeResources

I'm not sure why any of this would cause that error, but it's 1 difference between how OTX is packaged and how Tahoma is packaged. This is unfortunately beyond me.

**Comment by artisteacher** [comment]
For future reference, it seems that this is an issue with the Xcode settings:
<img width="543" alt="Screen Shot 2020-09-04 at 8 04 02 PM" src="https://user-images.githubusercontent.com/21159116/92292182-d796db00-eee9-11ea-86bf-936292f02f3a.png">
Under code signing identity, you need to choose "Other" and then delete all the text there. 

I think I've resolved the issue. If anyone wants to test, [here is the link](https://drive.google.com/file/d/1N7_PfL1rUMlvBe5Of4uYpW9_4ESARTuv/view?usp=sharing).

**Comment by manongjohn** [comment]
I tested it and it works as normal being security blocked initially, instead of saying it's damaged.

**Comment by artisteacher** [comment]
Fantastic. @turtletooth, please update the macOS release when you can.

**Comment by turtletooth** [comment]
@artisteacher Thanks for the updated release.  I swapped out the download last night.  Can someone check to make sure it works?
