### ISSUE TITLE
Found the location of the cause of <> tags being written.

### ISSUE THREAD

**Issue by jeremybullock** [turtletooth/tahoma#178]
I managed to create a scene that would consistently create a <> keyframe.

If you download the scene and move the keyframe on frame 7 to frame 20(ish?) it creates a <> keyframe.

Reverting opentoonz/opentoonz#2647 seems to keep the <> from being written.  Something in that pr is confusing the logic.

You can watch the debug values in setkeyframe in tstageobject.cpp to see the m_type of the keyframe during paste.

[sandbox.zip](https://github.com/turtletooth/tahoma/files/5237506/sandbox.zip)

**Comment by manongjohn** [comment]
That logic also produced the `<n>` when pasting before the 1st keyframe. Seems doing something the other way produces the `<>`.

If you aren't already working on it, I will take a look to see why it is doing that now that it can be easily duplicated.

**Comment by manongjohn** [comment]
I've reviewed this and I see what's going on.  

I noticed the keyframe data, when it's loaded into OT, doesn't have m_prevType set on any of the data correctly.  The logic is expecting the m_prevTypes to be set correctly so it can relink channels when inserting keys between others. Because m_prevType is None, it's perpetuating the issue and causing additional problems.

I need to look to see why the m_prevType is not being set correctly on loading.  Fixing that should resolve the issue.

Can you tell me how these keys were generated and in what order?  I want to verify what happens when they are being created.

**Comment by jeremybullock** [comment]
I don't think it's a save or loading issue.  When pasting in the example I gave above, you can see in the graph editor that the keyframe gets broken before saving or loading.

To get the bug, I created a simple scene and started copying and pasting keyframes and did a little tweaking in the graph editor all while saving regularly to see if I was getting the issue.

**Comment by manongjohn** [comment]
It's not from the initial saving of the scene. It is related to loading afterwards.

Somehow the m_prevType is not being set in the pegbar keyframe data when loading from a scene file, even though the keyframe itself is read and added to the pegbar.

Typically the m_prevType values are calculated on the fly or corrected after the fact. Somehow it's getting lost or not set properly along the way.

**Comment by manongjohn** [comment]
Scratch what I said for now. I didn't realize these are partial keyframes which is probably a factor in why this is happening.
