### ISSUE TITLE
Possible to move location of TahomaStuff? [SOLVED]

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma#207]
Hi.  One thing that appears to be different between Tahoma and OpenToonz is that during the installation, OT asks you where you would like the project/sandbox folders to go, which I really appreciate.  Using a SSD as my O/S drive, I don't like having frequently written-to folders placed there, and would rather they sit on a secondary drive, so my SSD doesn't have the writes rapidly beaten out of it (...plus, I generally don't like to clutter the O/S drive with projects and non-program stuff).

Can you not specify the TahomaStuff folder location, even after installation?  I know you can work around this by, perhaps, setting up a 'Test' project that you always use when you are wanting to be in 'sandbox' mode... which is what I will probably do.  But, I was wondering if the sandbox folder could be moved.

**Comment by manongjohn** [comment]
You should not move the tahomastuff folder.

Unlike the OT installation, Tahoma is built as a portable so the whole thing can be placed anywhere, which is why the tahomastuff folder is where it is at.  Unzip and run, no real installation.  OT's installation uses registry keys (Windows) or configuration files created in a user's home directory (macOS/Linux) to identify where the stuff folder is  While there is probably a way it can be tricked out to do that, I really don't recommend it.

You can always place the entire Tahoma folder on the secondary drive and run from there if you are concerned about how often it is writing to your primary drive.

In general for any OT variant, I would avoid using sandbox and would recommend establishing a Project Root folder where you want it (Preferences -> General). Create all new projects in the Project Root folder.  It also helps in upgrade processes since there will be no fear it will be lost when the stuff folder is updated or you want to run a newer version of Tahoma.

**Comment by ladlon** [comment]
Hi, manongjohn.  Thanks for the reply.

Ya, I get the whole portability purpose/reasoning, but I'm asking in the context of someone who is using Tahoma because of the  updates/improvements, as opposed to wanting a portable version (...although it certainly is cool to have the portable option).  Otherwise, I'd just stick with regular OpenToonz.   I wasn't sure if there was some means to move it (and forfeit the portability) for the sake of not having project files on the O/S drive.

But, ya, I figured I could just make a 'Test' or 'Sandbox' project, and hope to remember to click on that every time I start (for a 'just goofing around, testing stuff' session.  I just wasn't sure if installing Tahoma on the O/S drive would result in it constantly updating SOMETHING in the TahomaStuff folder, regardless of whether I was doing a unique (different drive location) project or not.

**Comment by manongjohn** [comment]
Well, it is possible.  Here is how for Windows:

1. Edit this file and modify the `C:\\Tahoma stuff` to where you want to put it

[Tahoma_registry.reg.txt](https://github.com/turtletooth/tahoma/files/5278625/Tahoma_registry.reg.txt)

2. Remove the .txt and double click to apply to registry

3. Move and rename the `Tahoma\tahomastuff` to wherever you want to put the stuff file

4. Start Tahoma.

**Comment by ladlon** [comment]
Neat...  Thanks for that!
