### ISSUE TITLE
Beta To Do

### ISSUE THREAD

**Issue by turtletooth** [turtletooth/tahoma#75]
- [x] Add Status Bar tip for ruler tool
- [x] Fix warnings on stop motion controller
- [x] Make what's new
- [x] Make website for Tahoma
- [x]  Metadata to stop motion tests
- [x] Allow Project Changing in File Menu
- [x] Export Project Popup

**Comment by artisteacher** [comment]
- [ ] The online manual should switch out OpenToonz branding/references for Tahoma - and a couple Tahoma specific things should be updated.
- [ ] A Tahoma specific forum should probably replace the OpenToonz Google Group in the Help menu

**Comment by turtletooth** [comment]
I think I'm just going to remove the reference to the forum for now.  Does that work?

**Comment by artisteacher** [comment]
> I think I'm just going to remove the reference to the forum for now.

Sure. It's better to take some time to choose the best platform.

On a related note, I'd like to add the following to the bottom of the install page of the manual:

.. tip:: For macOS 10.15 and later, the first time you open Tahoma, there may be an error message saying Tahoma cannot be opened. Choose “Cancel” and open System Preferences. Under ``Security & Privacy``&rarr;`` General``, select “Open Anyway.” Then choose “Open” in the next dialog. Afterwards, Tahoma will open normally. 

.. tip:: For older versions of macOS, open through Finder the first time. Right-click on Tahoma and select “Open”. Then choose “Open Anyway”. Afterwards, Tahoma will open normally.

Power users know how to override the Gatekeeper protections, but a lot of other users might not. There didn't seem to be an obvious way to add a pull request since it's a fork of the OT manual.

**Comment by turtletooth** [comment]
@artisteacher Can I give you commit privileges on the manual?

**Comment by artisteacher** [comment]
Sure!

**Comment by turtletooth** [comment]
@artisteacher You should see a pending invitation to both the docs and the website repos.
